# Generated by Django 6.0.3 on 2026-04-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_wishlistitem_garment_alter_wishlistitem_user'),
        ('orders', '0002_orderitem_unique_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='garments',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='clothes.garment'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('code', 'Promo code'), ('garment', 'Garment Discount'), ('category', 'Category Discount'), ('order', 'Order Discount')], default='code', max_length=20),
        ),
    ]
