# Generated by Django 6.0.3 on 2026-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_garment_image_garment_stock_alter_category_name_and_more'),
        ('orders', '0002_order_payment_type_promotion_order_promotion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('pod', 'Payment on delivery'), ('card', 'Card payment'), ('paypal', 'PayPal')], default='pod', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='clothes.category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='garments',
        ),
        migrations.AddField(
            model_name='promotion',
            name='garments',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='clothes.garment'),
        ),
    ]
