# Generated by Django 6.0.3 on 2026-03-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_price_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='garments',
        ),
    ]
