# Generated by Django 6.0.3 on 2026-04-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_promotion_garments_promotion_max_uses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='garments',
        ),
    ]
