# Generated by Django 6.0.3 on 2026-03-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_promotion_garments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('code', 'Promo code'), ('garment', 'Garment Discount'), ('category', 'Category'), ('order', 'Order Discount')], default='', max_length=20),
        ),
    ]
