# Generated by Django 6.0.3 on 2026-04-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_promotion_code_alter_promotion_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='garment',
        ),
    ]
