# Generated by Django 6.0.3 on 2026-04-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_promotion_alter_orderitem_promotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='promotion',
        ),
    ]
