# Generated by Django 6.0.3 on 2026-04-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_wishlistitem'),
        ('orders', '0006_remove_orderitem_garment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='garment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clothes.product'),
        ),
    ]
