# Generated by Django 6.0.3 on 2026-04-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0018_wishlistitem'),
        ('orders', '0007_orderitem_garment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='garment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='clothes.product'),
        ),
    ]
