# Generated by Django 6.0.3 on 2026-04-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_orderitem_garment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='garment',
            new_name='product',
        ),
    ]
