# Generated by Django 6.0.3 on 2026-04-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0010_alter_lookbookimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('code', 'Promo code'), ('garment', 'Garment Discount'), ('category', 'Category Discount'), ('order', 'Order Discount')], default='code', max_length=20)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='clothes.category')),
                ('garments', models.ManyToManyField(blank=True, related_name='promotions', to='clothes.garment')),
            ],
        ),
    ]
