# Generated by Django 6.0.3 on 2026-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_alter_category_options_alter_color_options_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='clothes.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Discount Percent'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='garments',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='clothes.garment', verbose_name='Garments'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Uses'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Order Amount'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='times_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Times Used'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type',
            field=models.CharField(choices=[('code', 'Promo code'), ('garment', 'Garment Discount'), ('category', 'Category Discount'), ('order', 'Order Discount')], default='code', max_length=20, verbose_name='Promo Type'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Valid From'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Valid Until'),
        ),
    ]
