# Generated by Django 6.0.3 on 2026-05-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_options_alter_promotion_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Code'),
        ),
    ]
