# Generated by Django 6.0.3 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.RemoveField(
            model_name='garment',
            name='category',
        ),
        migrations.AddField(
            model_name='garment',
            name='category',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='garments', to='clothes.category'),
        ),
    ]
