# Generated by Django 6.0.3 on 2026-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_category_color_size_delete_order_garment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
