# Generated by Django 6.0.3 on 2026-04-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_alter_category_profile_image_remove_garment_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='garments/'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.ManyToManyField(related_name='garments', to='clothes.category'),
        ),
    ]
