# Generated by Django 6.0.3 on 2026-04-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_garment_main_image_alter_garment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
