# Generated by Django 6.0.3 on 2026-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_garment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('dress', 'Dress'), ('pants', 'Pants'), ('skirts', 'Skirts'), ('shirts', 'Shirts'), ('jackets', 'Jackets'), ('cardigans', 'Cardigans'), ('tops', 'Tops')], max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='garment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='size',
        ),
        migrations.AddField(
            model_name='garment',
            name='color',
            field=models.ManyToManyField(related_name='garments', to='clothes.color'),
        ),
        migrations.AddField(
            model_name='garment',
            name='size',
            field=models.ManyToManyField(related_name='garments', to='clothes.size'),
        ),
    ]
