# Generated by Django 6.0.3 on 2026-04-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_garment_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='new',
        ),
        migrations.AddField(
            model_name='garment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
