# Generated by Django 6.0.3 on 2026-03-19 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_garment_image_garment_stock_alter_category_name_and_more'),
        ('orders', '0004_remove_promotion_garments'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments', to='orders.promotion'),
        ),
    ]
