# Generated by Django 6.0.3 on 2026-03-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_garment_promotion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
