# Generated by Django 6.0.3 on 2026-03-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('dress', 'Dress'), ('pants', 'Pants'), ('skirts', 'Skirts'), ('shirts', 'Shirts'), ('jackets', 'Jackets'), ('cardigans', 'Cardigans'), ('tops', 'Tops')], default='dress', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('brown', 'Brown')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('uni size', 'Uni size')], max_length=50, unique=True),
        ),
    ]
