# Generated by Django 6.0.3 on 2026-03-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_category_profile_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('gray', 'Gray'), ('brown', 'Brown')], default='black', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('uni size', 'Uni size')], default='xs', max_length=50, unique=True),
        ),
    ]
