# Generated by Django 6.0.3 on 2026-04-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_alter_wishlistitem_garment_alter_wishlistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False),
        ),
    ]
