# Generated by Django 6.0.3 on 2026-03-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(default='black', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(default='Uni size', max_length=50, unique=True),
        ),
    ]
