# Generated by Django 6.0.3 on 2026-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0008_category_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='garmentimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
