# Generated by Django 6.0.3 on 2026-04-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_alter_garment_main_image_alter_garmentimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lookbookimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='lookbookimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='garment',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='garments/'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='garmentimage',
            name='image',
            field=models.ImageField(upload_to='garmentImages/'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='garment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wished', to='clothes.garment'),
        ),
    ]
