# Generated by Django 6.0.3 on 2026-05-04 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0010_alter_lookbookimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterModelOptions(
            name='garment',
            options={'verbose_name': 'Garment', 'verbose_name_plural': 'Garments'},
        ),
        migrations.AlterModelOptions(
            name='garmentimage',
            options={'verbose_name': 'Garment Image', 'verbose_name_plural': 'Garment Images'},
        ),
        migrations.AlterModelOptions(
            name='lookbookimage',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'size', 'verbose_name_plural': 'sizes'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='garment',
            name='description_bg',
            field=models.TextField(blank=True, null=True, verbose_name='Garment description'),
        ),
        migrations.AddField(
            model_name='garment',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Garment description'),
        ),
        migrations.AddField(
            model_name='garment',
            name='name_bg',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Garment name'),
        ),
        migrations.AddField(
            model_name='garment',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Garment name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='profile image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, verbose_name='trending'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(blank=True, max_length=7, unique=True, verbose_name='hex code'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.ManyToManyField(related_name='garments', to='clothes.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Garment description'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='garments/', verbose_name='Main image'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Garment name'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='garmentimage',
            name='garment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothes.garment', verbose_name='Garment'),
        ),
        migrations.AlterField(
            model_name='garmentimage',
            name='image',
            field=models.ImageField(upload_to='garmentImages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='lookbookimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='lookbookimage',
            name='image',
            field=models.ImageField(upload_to='lookbook/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='garment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.garment', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.size', verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='garment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wished', to='clothes.garment', verbose_name='Garment'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
