# Generated by Django 6.0.3 on 2026-03-28 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_alter_category_name'),
        ('orders', '0005_alter_promotion_code_alter_promotion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garments', to='clothes.category'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='promotion',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garments', to='orders.promotion'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='stock',
            field=models.IntegerField(default=None),
        ),
    ]
