# Generated by Django 6.0.3 on 2026-05-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0011_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_bg',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garment name'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='name_bg',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garment name'),
        ),
        migrations.AlterField(
            model_name='garment',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garment name'),
        ),
    ]
