# Generated by Django 6.0.3 on 2026-03-29 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0012_alter_garment_category_alter_garment_promotion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='garments/')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothes.garment')),
            ],
        ),
    ]
