# Generated by Django 6.0.3 on 2026-03-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0013_garmentimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garment',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='size',
        ),
        migrations.RemoveField(
            model_name='garment',
            name='stock',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.color')),
                ('garment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.garment')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='clothes.size')),
            ],
            options={
                'unique_together': {('garment', 'size', 'color')},
            },
        ),
    ]
