# Generated by Django 6.0.3 on 2026-03-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0014_rename_image_garment_profile_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['garment', 'size', 'color'], name='clothes_pro_garment_bbf3dd_idx'),
        ),
    ]
