# Generated by Django 6.0.3 on 2026-03-30 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0015_product_clothes_pro_garment_bbf3dd_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='promotion',
        ),
    ]
