# Generated by Django 6.0.3 on 2026-04-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0016_remove_garment_promotion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='garment',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
