# Generated by Django 6.0.3 on 2026-04-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(to='clothes.garment'),
        ),
    ]
