# Generated by Django 6.0.3 on 2026-03-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_appuser_is_active_alter_appuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telephone_number',
            field=models.CharField(max_length=20),
        ),
    ]
