# Generated by Django 6.0.3 on 2026-04-08 15:25

import fashionWebsite.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_appuser_options_remove_appuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[fashionWebsite.accounts.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[fashionWebsite.accounts.validators.name_validator]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[fashionWebsite.accounts.validators.name_validator]),
        ),
    ]
