# Generated by Django 6.0.3 on 2026-04-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_first_name_alter_customer_last_name_and_more'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, to='clothes.garment'),
        ),
    ]
