# Generated by Django 6.0.3 on 2026-04-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_favorites'),
        ('clothes', '0002_alter_category_profile_image_remove_garment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(to='clothes.garment'),
        ),
    ]
