# Generated by Django 6.0.3 on 2026-05-04 09:03

import django.db.models.deletion
import fashionWebsite.accounts.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_favorites'),
        ('clothes', '0011_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'App Users'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Staff status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='favorites',
            field=models.ManyToManyField(to='clothes.garment', verbose_name='Favorites'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=100, validators=[fashionWebsite.accounts.validators.name_validator], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=100, validators=[fashionWebsite.accounts.validators.name_validator], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[fashionWebsite.accounts.validators.name_validator], verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone_number',
            field=models.CharField(max_length=20, verbose_name='Telephone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
