# Generated by Django 6.0.3 on 2026-05-06 09:17

import fashionWebsite.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default='', max_length=100, validators=[fashionWebsite.accounts.validators.name_validator], verbose_name='Middle Name'),
        ),
    ]
