# Generated by Django 6.0.3 on 2026-04-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
