# Generated by Django 6.0.3 on 2026-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Newsletter Subscriber'},
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Subscribed'),
        ),
    ]
