# Generated by Django 6.0.3 on 2026-05-06 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_newslettersubscriber_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token'),
        ),
    ]
